[workspace]
[package]
version = "0.1.0"
name = "polygon-pos-light-script"
edition = "2021"

[dependencies]
sp1-core = { git = "https://github.com/succinctlabs/sp1.git" }


[build-dependencies]
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git" }
