[workspace]
[package]
version = "0.1.0"
name = "polygon-pos-light-program"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
sp1-precompiles = { git = "https://github.com/succinctlabs/sp1.git" }
poly_milestone = { path = "../milestone" }
